image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Start Server
    command: |
      cd .devcontainer/build-assets
      python db_setup.py
    # Replace the commands with the appropriate paths to your scripts or server startup commands

ports:
  - port: 5000
    onOpen: ignore
