image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Server
    command: python server.py
    # Replace `server.py` with the name of your Python script that starts the server
    # You might need to adjust the command if the Python script is located in a different directory

ports:
  - port: 5000
    onOpen: ignore
